//
//  TestModel.swift
//  ConvertTestVasiliev
//
//  Created by Владислав on 03.04.2021.
//

import Foundation

struct DataCurrency: Decodable {
    let currencies: DataCurrencyName
    let status: String
}

struct DataCurrencyName: Decodable {
    let STN: String?
    let XAG: String?
    let XAU: String?
    let PLN: String?
    let UGX: String?
    let GGP: String?
    let MWK: String?
    let NAD: String?
    let ALL: String?
    let BHD: String?
    let JEP: String?
    let BWP: String?
    let MRU: String?
    let BMD: String?
    let MNT: String?
    let FKP: String?
    let PYG: String?
    let AUD: String?
    let KYD: String?
    let RWF: String?
    let WST: String?
    let SHP: String?
    let SOS: String?
    let SSP: String?
    let BIF: String?
    let SEK: String?
    let CUC: String?
    let BTN: String?
    let MOP: String?
    let XDR: String?
    let IMP: String?
    let INR: String?
    let BYN: String?
    let BOB: String?
    let SRD: String?
    let GEL: String?
    let ZWL: String?
    let EUR: String?
    let BBD: String?
    let RSD: String?
    let SDG: String?
    let VND: String?
    let VES: String?
    let ZMW: String?
    let KGS: String?
    let HUF: String?
    let BND: String?
    let BAM: String?
    let CVE: String?
    let BGN: String?
    let NOK: String?
    let BRL: String?
    let JPY: String?
    let HRK: String?
    let HKD: String?
    let ISK: String?
    let IDR: String?
    let KRW: String?
    let KHR: String?
    let XAF: String?
    let CHF: String?
    let MXN: String?
    let PHP: String?
    let RON: String?
    let RUB: String?
    let SGD: String?
    let AED: String?
    let KWD: String?
    let CAD: String?
    let PKR: String?
    let CLP: String?
    let CNY: String?
    let COP: String?
    let AOA: String?
    let KMF: String?
    let CRC: String?
    let CUP: String?
    let GNF: String?
    let NZD: String?
    let EGP: String?
    let DJF: String?
    let ANG: String?
    let DOP: String?
    let JOD: String?
    let AZN: String?
    let SVC: String?
    let NGN: String?
    let ERN: String?
    let SZL: String?
    let DKK: String?
    let ETB: String?
    let FJD: String?
    let XPF: String?
    let GMD: String?
    let AFN: String?
    let GHS: String?
    let GIP: String?
    let GTQ: String?
    let HNL: String?
    let GYD: String?
    let HTG: String?
    let XCD: String?
    let GBP: String?
    let AMD: String?
    let IRR: String?
    let JMD: String?
    let IQD: String?
    let KZT: String?
    let KES: String?
    let ILS: String?
    let LYD: String?
    let LSL: String?
    let LBP: String?
    let LRD: String?
    let AWG: String?
    let MKD: String?
    let LAK: String?
    let MGA: String?
    let ZAR: String?
    let MDL: String?
    let MVR: String?
    let MUR: String?
    let MMK: String?
    let MAD: String?
    let XOF: String?
    let MZN: String?
    let MYR: String?
    let OMR: String?
    let NIO: String?
    let NPR: String?
    let PAB: String?
    let PGK: String?
    let PEN: String?
    let ARS: String?
    let SAR: String?
    let QAR: String?
    let SCR: String?
    let SLL: String?
    let LKR: String?
    let SBD: String?
    let VUV: String?
    let USD: String?
    let DZD: String?
    let BDT: String?
    let BSD: String?
    let BZD: String?
    let CDF: String?
    let UAH: String?
    let YER: String?
    let TMT: String?
    let UZS: String?
    let UYU: String?
    let CZK: String?
    let SYP: String?
    let TJS: String?
    let TWD: String?
    let TZS: String?
    let TOP: String?
    let TTD: String?
    let THB: String?
    let TRY: String?
    let TND: String?
}

struct DecodedArray: Decodable {
    
    var array: [DataCurrencyName]
    
    private struct DynamicCodingKeys: CodingKey {
        
        var stringValue: String
        init?(stringValue: String) {
            self.stringValue = stringValue
        }
        
        var intValue: Int?
        init?(intValue: Int) {
            return nil
        }
    }
    
    init(from decoder: Decoder) throws {
        
        let container = try decoder.container(keyedBy: DynamicCodingKeys.self)
        
        var tempArray = [DataCurrencyName]()
        
        for key in container.allKeys {
            
            let decodedObject = try container.decode(DataCurrencyName.self, forKey: DynamicCodingKeys(stringValue: key.stringValue)!)
            tempArray.append(decodedObject)
        }
        
        array = tempArray
    }
}


/*
 let STN: String
 let XAG: String
 let XAU: String
 let PLN: String
 let UGX: String
 let GGP: String
 let MWK: String
 let NAD: String
 let ALL: String
 let BHD: String
 let JEP: String
 let BWP: String
 let MRU: String
 let BMD: String
 let MNT: String
 let FKP: String
 let PYG: String
 let AUD: String
 let KYD: String
 let RWF: String
 let WST: String
 let SHP: String
 let SOS: String
 let SSP: String
 let BIF: String
 let SEK: String
 let CUC: String
 let BTN: String
 let MOP: String
 let XDR: String
 let IMP: String
 let INR: String
 let BYN: String
 let BOB: String
 let SRD: String
 let GEL: String
 let ZWL: String
 let EUR: String
 let BBD: String
 let RSD: String
 let SDG: String
 let VND: String
 let VES: String
 let ZMW: String
 let KGS: String
 let HUF: String
 let BND: String
 let BAM: String
 let CVE: String
 let BGN: String
 let NOK: String
 let BRL: String
 let JPY: String
 let HRK: String
 let HKD: String
 let ISK: String
 let IDR: String
 let KRW: String
 let KHR: String
 let XAF: String
 let CHF: String
 let MXN: String
 let PHP: String
 let RON: String
 let RUB: String
 let SGD: String
 let AED: String
 let KWD: String
 let CAD: String
 let PKR: String
 let CLP: String
 let CNY: String
 let COP: String
 let AOA: String
 let KMF: String
 let CRC: String
 let CUP: String
 let GNF: String
 let NZD: String
 let EGP: String
 let DJF: String
 let ANG: String
 let DOP: String
 let JOD: String
 let AZN: String
 let SVC: String
 let NGN: String
 let ERN: String
 let SZL: String
 let DKK: String
 let ETB: String
 let FJD: String
 let XPF: String
 let GMD: String
 let AFN: String
 let GHS: String
 let GIP: String
 let GTQ: String
 let HNL: String
 let GYD: String
 let HTG: String
 let XCD: String
 let GBP: String
 let AMD: String
 let IRR: String
 let JMD: String
 let IQD: String
 let KZT: String
 let KES: String
 let ILS: String
 let LYD: String
 let LSL: String
 let LBP: String
 let LRD: String
 let AWG: String
 let MKD: String
 let LAK: String
 let MGA: String
 let ZAR: String
 let MDL: String
 let MVR: String
 let MUR: String
 let MMK: String
 let MAD: String
 let XOF: String
 let MZN: String
 let MYR: String
 let OMR: String
 let NIO: String
 let NPR: String
 let PAB: String
 let PGK: String
 let PEN: String
 let ARS: String
 let SAR: String
 let QAR: String
 let SCR: String
 let SLL: String
 let LKR: String
 let SBD: String
 let VUV: String
 let USD: String
 let DZD: String
 let BDT: String
 let BSD: String
 let BZD: String
 let CDF: String
 let UAH: String
 let YER: String
 let TMT: String
 let UZS: String
 let UYU: String
 let CZK: String
 let SYP: String
 let TJS: String
 let TWD: String
 let TZS: String
 let TOP: String
 let TTD: String
 let THB: String
 let TRY: String
 let TND: String
 */



/*
 let STN: String?
 let XAG: String?
 let XAU: String?
 let PLN: String?
 let UGX: String?
 let GGP: String?
 let MWK: String?
 let NAD: String?
 let ALL: String?
 let BHD: String?
 let JEP: String?
 let BWP: String?
 let MRU: String?
 let BMD: String?
 let MNT: String?
 let FKP: String?
 let PYG: String?
 let AUD: String?
 let KYD: String?
 let RWF: String?
 let WST: String?
 let SHP: String?
 let SOS: String?
 let SSP: String?
 let BIF: String?
 let SEK: String?
 let CUC: String?
 let BTN: String?
 let MOP: String?
 let XDR: String?
 let IMP: String?
 let INR: String?
 let BYN: String?
 let BOB: String?
 let SRD: String?
 let GEL: String?
 let ZWL: String?
 let EUR: String?
 let BBD: String?
 let RSD: String?
 let SDG: String?
 let VND: String?
 let VES: String?
 let ZMW: String?
 let KGS: String?
 let HUF: String?
 let BND: String?
 let BAM: String?
 let CVE: String?
 let BGN: String?
 let NOK: String?
 let BRL: String?
 let JPY: String?
 let HRK: String?
 let HKD: String?
 let ISK: String?
 let IDR: String?
 let KRW: String?
 let KHR: String?
 let XAF: String?
 let CHF: String?
 let MXN: String?
 let PHP: String?
 let RON: String?
 let RUB: String?
 let SGD: String?
 let AED: String?
 let KWD: String?
 let CAD: String?
 let PKR: String?
 let CLP: String?
 let CNY: String?
 let COP: String?
 let AOA: String?
 let KMF: String?
 let CRC: String?
 let CUP: String?
 let GNF: String?
 let NZD: String?
 let EGP: String?
 let DJF: String?
 let ANG: String?
 let DOP: String?
 let JOD: String?
 let AZN: String?
 let SVC: String?
 let NGN: String?
 let ERN: String?
 let SZL: String?
 let DKK: String?
 let ETB: String?
 let FJD: String?
 let XPF: String?
 let GMD: String?
 let AFN: String?
 let GHS: String?
 let GIP: String?
 let GTQ: String?
 let HNL: String?
 let GYD: String?
 let HTG: String?
 let XCD: String?
 let GBP: String?
 let AMD: String?
 let IRR: String?
 let JMD: String?
 let IQD: String?
 let KZT: String?
 let KES: String?
 let ILS: String?
 let LYD: String?
 let LSL: String?
 let LBP: String?
 let LRD: String?
 let AWG: String?
 let MKD: String?
 let LAK: String?
 let MGA: String?
 let ZAR: String?
 let MDL: String?
 let MVR: String?
 let MUR: String?
 let MMK: String?
 let MAD: String?
 let XOF: String?
 let MZN: String?
 let MYR: String?
 let OMR: String?
 let NIO: String?
 let NPR: String?
 let PAB: String?
 let PGK: String?
 let PEN: String?
 let ARS: String?
 let SAR: String?
 let QAR: String?
 let SCR: String?
 let SLL: String?
 let LKR: String?
 let SBD: String?
 let VUV: String?
 let USD: String?
 let DZD: String?
 let BDT: String?
 let BSD: String?
 let BZD: String?
 let CDF: String?
 let UAH: String?
 let YER: String?
 let TMT: String?
 let UZS: String?
 let UYU: String?
 let CZK: String?
 let SYP: String?
 let TJS: String?
 let TWD: String?
 let TZS: String?
 let TOP: String?
 let TTD: String?
 let THB: String?
 let TRY: String?
 let TND: String?
 */
